In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline

In [18]:
df = pd.read_csv("https://raw.githubusercontent.com/niteen11/DataAnalyticsAcademy/master/Python/dataset_diabetes/diabetic_data.csv")

URLError: <urlopen error [SSL: TLSV1_ALERT_DECODE_ERROR] tlsv1 alert decode error (_ssl.c:1076)>

In [ ]:
##missing_values=['?','Unknown/Invalid']

##,na_values = missing_values)

In [2]:
df.head(50)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),?,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),?,3,1,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),?,1,1,7,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),?,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),?,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),?,1,1,7,9,...,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),?,2,1,4,7,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),?,1,3,7,7,...,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),?,1,6,7,10,...,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),?,3,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),?,1,3,7,12,...,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),?,1,1,7,4,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),?,1,1,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),?,1,1,7,5,...,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,?,Male,[70-80),?,3,6,2,6,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,?,Female,[50-60),?,2,1,4,2,...,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,?,Male,[60-70),?,2,1,4,2,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),?,2,1,4,2,...,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),?,2,6,1,11,...,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),?,3,1,2,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),?,1,1,7,1,...,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),?,1,3,7,6,...,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),?,1,1,1,2,...,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),?,2,1,2,10,...,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),?,1,2,7,5,...,No,No,No,No,No,No,No,Ch,Yes,>30
30,253380,56480238,AfricanAmerican,Female,[60-70),?,1,1,7,6,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
31,253722,96664626,AfricanAmerican,Male,[70-80),?,1,5,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
32,260166,80845353,Caucasian,Female,[70-80),?,1,1,7,6,...,No,Steady,No,No,No,No,No,No,Yes,>30
33,293058,114715242,Caucasian,Male,[60-70),?,2,6,2,5,...,No,Steady,No,No,No,No,No,No,Yes,>30
34,293118,3327282,Caucasian,Female,[70-80),?,2,11,2,5,...,No,Down,No,No,No,No,No,Ch,Yes,NO
35,325848,63023292,Caucasian,Female,[60-70),?,1,1,7,2,...,No,Down,No,No,No,No,No,Ch,Yes,>30
36,325866,98427861,Caucasian,Female,[70-80),?,3,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,NO
37,326028,112002975,Caucasian,Female,[60-70),?,1,1,7,4,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
38,358776,101002446,Caucasian,Male,[70-80),?,1,6,7,7,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
39,377268,104672268,Caucasian,Male,[50-60),?,2,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),?,1,2,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
41,419304,99715041,Caucasian,Male,[40-50),?,2,1,2,7,...,No,Steady,No,No,No,No,No,No,Yes,>30
42,421194,96435585,Caucasian,Female,[70-80),?,2,1,1,13,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
43,449142,66274866,Caucasian,Male,[50-60),?,1,1,7,3,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
44,450210,80177094,Caucasian,Female,[80-90),?,1,11,7,7,...,No,Steady,No,No,No,No,No,No,Yes,NO
45,464994,106936875,Caucasian,Female,[40-50),?,3,1,2,2,...,No,Steady,No,No,No,No,No,No,Yes,NO
46,486156,86240259,Caucasian,Female,[70-80),?,3,5,4,9,...,No,Down,No,No,No,No,No,Ch,Yes,<30
47,498030,51838164,Caucasian,Male,[70-80),?,3,3,4,9,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
48,537834,90097839,Caucasian,Male,[50-60),?,3,1,2,6,...,No,Up,No,No,No,No,No,Ch,Yes,NO
49,544194,34997814,Caucasian,Male,[60-70),?,2,6,4,11,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

    identifying the headers

In [3]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [4]:
# creating new data frame
drop_cols = ['patient_nbr','weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']
df.drop(drop_cols, inplace = True, axis = 1)

In [5]:
df.head(50)

    encounter_id             race  gender       age
0        2278392        Caucasian  Female    [0-10)
1         149190        Caucasian  Female   [10-20)
2          64410  AfricanAmerican  Female   [20-30)
3         500364        Caucasian    Male   [30-40)
4          16680        Caucasian    Male   [40-50)
5          35754        Caucasian    Male   [50-60)
6          55842        Caucasian    Male   [60-70)
7          63768        Caucasian    Male   [70-80)
8          12522        Caucasian  Female   [80-90)
9          15738        Caucasian  Female  [90-100)
10         28236  AfricanAmerican  Female   [40-50)
11         36900  AfricanAmerican    Male   [60-70)
12         40926        Caucasian  Female   [40-50)
13         42570        Caucasian    Male   [80-90)
14         62256  AfricanAmerican  Female   [60-70)
15         73578  AfricanAmerican    Male   [60-70)
16         77076  AfricanAmerican    Male   [50-60)
17         84222        Caucasian  Female   [50-60)
18         89682  AfricanAmerican    Male   [70-80)
19        148530                ?    Male   [70-80)
20        150006                ?  Female   [50-60)
21        150048                ?    Male   [60-70)
22        182796  AfricanAmerican  Female   [70-80)
23        183930        Caucasian  Female   [80-90)
24        216156  AfricanAmerican  Female   [70-80)
25        221634            Other  Female   [50-60)
26        236316        Caucasian    Male   [80-90)
27        248916        Caucasian  Female   [50-60)
28        250872        Caucasian    Male   [20-30)
29        252822        Caucasian  Female   [80-90)
30        253380  AfricanAmerican  Female   [60-70)
31        253722  AfricanAmerican    Male   [70-80)
32        260166        Caucasian  Female   [70-80)
33        293058        Caucasian    Male   [60-70)
34        293118        Caucasian  Female   [70-80)
35        325848        Caucasian  Female   [60-70)
36        325866        Caucasian  Female   [70-80)
37        326028        Caucasian  Female   [60-70)
38        358776        Caucasian    Male   [70-80)
39        377268        Caucasian    Male   [50-60)
40        383430        Caucasian  Female   [70-80)
41        419304        Caucasian    Male   [40-50)
42        421194        Caucasian  Female   [70-80)
43        449142        Caucasian    Male   [50-60)
44        450210        Caucasian  Female   [80-90)
45        464994        Caucasian  Female   [40-50)
46        486156        Caucasian  Female   [70-80)
47        498030        Caucasian    Male   [70-80)
48        537834        Caucasian    Male   [50-60)
49        544194        Caucasian    Male   [60-70)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   encounter_id  101766 non-null  int64
 1   race          101766 non-null  object
 2   gender        101766 non-null  object
 3   age           101766 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.9+ MB

In [7]:
df.shape

(101766, 4)

In [8]:
df['encounter_id'] = pd.to_numeric(df['encounter_id'], errors = 'coerce')

In [9]:
df['age']= df['age'].str.strip('[)')

In [10]:
df.head(50)

    encounter_id             race  gender     age
0        2278392        Caucasian  Female    0-10
1         149190        Caucasian  Female   10-20
2          64410  AfricanAmerican  Female   20-30
3         500364        Caucasian    Male   30-40
4          16680        Caucasian    Male   40-50
5          35754        Caucasian    Male   50-60
6          55842        Caucasian    Male   60-70
7          63768        Caucasian    Male   70-80
8          12522        Caucasian  Female   80-90
9          15738        Caucasian  Female  90-100
10         28236  AfricanAmerican  Female   40-50
11         36900  AfricanAmerican    Male   60-70
12         40926        Caucasian  Female   40-50
13         42570        Caucasian    Male   80-90
14         62256  AfricanAmerican  Female   60-70
15         73578  AfricanAmerican    Male   60-70
16         77076  AfricanAmerican    Male   50-60
17         84222        Caucasian  Female   50-60
18         89682  AfricanAmerican    Male   70-80
19        148530                ?    Male   70-80
20        150006                ?  Female   50-60
21        150048                ?    Male   60-70
22        182796  AfricanAmerican  Female   70-80
23        183930        Caucasian  Female   80-90
24        216156  AfricanAmerican  Female   70-80
25        221634            Other  Female   50-60
26        236316        Caucasian    Male   80-90
27        248916        Caucasian  Female   50-60
28        250872        Caucasian    Male   20-30
29        252822        Caucasian  Female   80-90
30        253380  AfricanAmerican  Female   60-70
31        253722  AfricanAmerican    Male   70-80
32        260166        Caucasian  Female   70-80
33        293058        Caucasian    Male   60-70
34        293118        Caucasian  Female   70-80
35        325848        Caucasian  Female   60-70
36        325866        Caucasian  Female   70-80
37        326028        Caucasian  Female   60-70
38        358776        Caucasian    Male   70-80
39        377268        Caucasian    Male   50-60
40        383430        Caucasian  Female   70-80
41        419304        Caucasian    Male   40-50
42        421194        Caucasian  Female   70-80
43        449142        Caucasian    Male   50-60
44        450210        Caucasian  Female   80-90
45        464994        Caucasian  Female   40-50
46        486156        Caucasian  Female   70-80
47        498030        Caucasian    Male   70-80
48        537834        Caucasian    Male   50-60
49        544194        Caucasian    Male   60-70

In [11]:
df.dropna().sum

<bound method DataFrame.sum of         encounter_id             race  gender    age
0            2278392        Caucasian  Female   0-10
1             149190        Caucasian  Female  10-20
2              64410  AfricanAmerican  Female  20-30
3             500364        Caucasian    Male  30-40
4              16680        Caucasian    Male  40-50
...              ...              ...     ...    ...
101761     443847548  AfricanAmerican    Male  70-80
101762     443847782  AfricanAmerican  Female  80-90
101763     443854148        Caucasian    Male  70-80
101764     443857166        Caucasian  Female  80-90
101765     443867222        Caucasian    Male  70-80

[101766 rows x 4 columns]>

In [12]:
df.head()

   encounter_id             race  gender    age
0       2278392        Caucasian  Female   0-10
1        149190        Caucasian  Female  10-20
2         64410  AfricanAmerican  Female  20-30
3        500364        Caucasian    Male  30-40
4         16680        Caucasian    Male  40-50

In [13]:
#sort and group
df.sort_values(['gender','race'], ascending=[True,False])

        encounter_id   race           gender    age
25            221634  Other           Female  50-60
98           1257282  Other           Female  50-60
106          1445010  Other           Female  50-60
136          2294130  Other           Female  60-70
271          2970666  Other           Female  50-60
...              ...    ...              ...    ...
101702     443186306      ?             Male  70-80
101715     443226344      ?             Male  50-60
30506       98634858  Other  Unknown/Invalid  70-80
75551      226864668      ?  Unknown/Invalid  60-70
82573      257364294      ?  Unknown/Invalid  70-80

[101766 rows x 4 columns]

In [14]:
df3 = df.groupby(['race','age']).size()

In [15]:
print(df3)

race             age
?                0-10          1
                 10-20         9
                 20-30        46
                 30-40        76
                 40-50       220
                 50-60       361
                 60-70       495
                 70-80       599
                 80-90       397
                 90-100       69
AfricanAmerican  0-10         16
                 10-20       209
                 20-30       540
                 30-40      1223
                 40-50      2787
                 50-60      4225
                 60-70      4232
                 70-80      3816
                 80-90      1817
                 90-100      345
Asian            0-10          2
                 10-20         2
                 20-30         6
                 30-40        15
                 40-50        52
                 50-60       123
                 60-70       160
                 70-80       180
                 80-90        90
                 90-100       11
Caucasian        0-10        136
                 10-20       438
                 20-30       975
                 30-40      2203
                 40-50      6131
                 50-60     11835
                 60-70     16693
                 70-80     20761
                 80-90     14602
                 90-100     2325
Hispanic         0-10          2
                 10-20        23
                 20-30        63
                 30-40       174
                 40-50       337
                 50-60       403
                 60-70       489
                 70-80       386
                 80-90       141
                 90-100       19
Other            0-10          4
                 10-20        10
                 20-30        27
                 30-40        84
                 40-50       158
                 50-60       309
                 60-70       414
                 70-80       326
                 80-90       150
                 90-100       24
dtype: int64

In [16]:
df2 = df.groupby(['race'])['encounter_id'].count().sort_values(ascending=True)
df2

race
Asian                641
Other               1506
Hispanic            2037
?                   2273
AfricanAmerican    19210
Caucasian          76099
Name: encounter_id, dtype: int64